# Importing the Required Libraries

In [ ]:
import numpy as np 
import pandas as pd 
import re
import nltk 


# Importing the Dataset

In [ ]:
data_source_url = "https://raw.githubusercontent.com/kolaveridi/kaggle-Twitter-US-Airline-Sentiment-/master/Tweets.csv"
airline_tweets = pd.read_csv(data_source_url)

In [ ]:
airline_tweets.head()

tweet_id  ...               user_timezone
0  570306133677760513  ...  Eastern Time (US & Canada)
1  570301130888122368  ...  Pacific Time (US & Canada)
2  570301083672813571  ...  Central Time (US & Canada)
3  570301031407624196  ...  Pacific Time (US & Canada)
4  570300817074462722  ...  Pacific Time (US & Canada)

[5 rows x 15 columns]

In [ ]:
features = airline_tweets.iloc[:, 10].values
labels = airline_tweets.iloc[:, 1].values


In [ ]:
features

array(['@VirginAmerica What @dhepburn said.',
       "@VirginAmerica plus you've added commercials to the experience... tacky.",
       "@VirginAmerica I didn't today... Must mean I need to take another trip!",
       ...,
       '@AmericanAir Please bring American Airlines to #BlackBerry10',
       "@AmericanAir you have my money, you change my flight, and don't answer your phones! Any other suggestions so I can make my commitment??",
       '@AmericanAir we have 8 ppl so we need 2 know how many seats are on the next flight. Plz put us on standby for 4 people on the next flight?'],
      dtype=object)

In [ ]:
labels

array(['neutral', 'positive', 'neutral', ..., 'neutral', 'negative',
       'neutral'], dtype=object)

# **Data Preprocessing**

In [ ]:
processed_features = []

for sentence in range(0, len(features)):
    # Remove all the special characters
    processed_feature = re.sub(r'\W', ' ', str(features[sentence]))

    # remove all single characters
    processed_feature= re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_feature)

    # Remove single characters from the start
    processed_feature = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_feature) 

    # Substituting multiple spaces with single space
    processed_feature = re.sub(r'\s+', ' ', processed_feature, flags=re.I)

    # Removing prefixed 'b'
    processed_feature = re.sub(r'^b\s+', '', processed_feature)
    
    # Removing numbers
    processed_feature = ''.join([i for i in processed_feature if not i.isnumeric()])

    # Converting to Lowercase
    processed_feature = processed_feature.lower()

    processed_features.append(processed_feature)

In [ ]:
processed_features

[' virginamerica what dhepburn said ',
 ' virginamerica plus you ve added commercials to the experience tacky ',
 ' virginamerica didn today must mean need to take another trip ',
 ' virginamerica it really aggressive to blast obnoxious entertainment in your guests faces amp they have little recourse',
 ' virginamerica and it a really big bad thing about it',
 ' virginamerica seriously would pay  flight for seats that didn have this playing it really the only bad thing about flying va',
 ' virginamerica yes nearly every time fly vx this ear worm won go away ',
 ' virginamerica really missed prime opportunity for men without hats parody there https co mwpggrezp',
 ' virginamerica well didn but now do d',
 ' virginamerica it was amazing and arrived an hour early you re too good to me ',
 ' virginamerica did you know that suicide is the second leading cause of death among teens  ',
 ' virginamerica lt  pretty graphics so much better than minimal iconography d',
 ' virginamerica this is su

In [ ]:

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# Feature Extraction

In the bag of words approach, each word has the same weight. The idea behind the **TF-IDF approach** is that the words that occur less in all the documents and more in individual document contribute more towards classification.

**TF-IDF** is a combination of two terms. Term frequency and Inverse Document frequency. They can be calculated as:

**TF  = (Frequency of a word in the document)/(Total words in the document)**

**IDF = Log((Total number of docs)/(Number of docs containing the word))** 

A high TF-IDF score is obtained by a term that has a high frequency in a document, and low document frequency in the corpus. 

For a word that appears in almost all documents, the IDF value approaches 0, making the tf-idf also come closer to 0.TF-IDF value is high when both IDF and TF values are high i.e the word is rare in the whole document but frequent in a document.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


**max_df** :is used for removing terms that appear too frequently, also known  as "corpus-specific stop words

=> max_df=0.8 means "ignore terms that appear in more than 80% of the documents".

**min_df** is used for removing terms that appear too infrequently.

=>min_df=7 means means "ignore terms that appear in less than 7 documents".

**max_features** = 2500, which means that it only uses the 2500 most frequently occurring words to create a bag of words feature vector. Words that occur less frequently are not very useful for classification.


In [ ]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))
processed_features = vectorizer.fit_transform(processed_features).toarray()

In [ ]:
vectorizer

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=0.8, max_features=2500,
                min_df=7, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents=None, sublinear_tf=False,
                token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
                vocabulary=None)

In [ ]:
len(vectorizer.vocabulary_)

2209

In [ ]:
vectorizer.vocabulary_

{'virginamerica': 2084,
 'said': 1679,
 'plus': 1461,
 'added': 27,
 'experience': 675,
 'today': 1960,
 'must': 1285,
 'mean': 1206,
 'need': 1297,
 'take': 1902,
 'another': 89,
 'trip': 1995,
 'really': 1559,
 'entertainment': 633,
 'amp': 80,
 'little': 1131,
 'big': 207,
 'bad': 170,
 'thing': 1932,
 'seriously': 1725,
 'would': 2178,
 'pay': 1407,
 'flight': 760,
 'seats': 1704,
 'playing': 1456,
 'flying': 784,
 'va': 2073,
 'yes': 2195,
 'nearly': 1296,
 'every': 651,
 'time': 1953,
 'fly': 780,
 'vx': 2093,
 'go': 856,
 'away': 163,
 'missed': 1257,
 'opportunity': 1362,
 'without': 2155,
 'https': 958,
 'co': 360,
 'well': 2130,
 'amazing': 73,
 'arrived': 120,
 'hour': 949,
 'early': 601,
 'good': 864,
 'know': 1064,
 'second': 1706,
 'leading': 1092,
 'cause': 298,
 'death': 494,
 'among': 78,
 'lt': 1170,
 'pretty': 1489,
 'much': 1282,
 'better': 205,
 'great': 870,
 'deal': 489,
 'already': 67,
 'thinking': 1935,
 'nd': 1294,
 'australia': 149,
 'even': 646,
 'gone': 862

In [ ]:
processed_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
pd.DataFrame(processed_features,columns=vectorizer.get_feature_names())

aa  aadvantage  abc  able  abq  ...  yup  yvr  yyz  zero  zone
0      0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
1      0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
2      0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
3      0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
4      0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
...    ...         ...  ...   ...  ...  ...  ...  ...  ...   ...   ...
14635  0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
14636  0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
14637  0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
14638  0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0
14639  0.0         0.0  0.0   0.0  0.0  ...  0.0  0.0  0.0   0.0   0.0

[14640 rows x 2209 columns]

**train_test_split** method takes the feature set as the first parameter, the label set as the second parameter, and a value for the test_size parameter. 

I specified a value of 0.2 for test_size which means that my data set will be split into two sets of 80% and 20% data.

We will use the 80% dataset for training and 20% dataset for testing.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(processed_features, labels, test_size=0.2, random_state=0)

# Training the Model

## Random Forest

This algorithm takes the decision tree concept further by producing a large number of decision tree

The approach first takes a random sample of the data and identifies a key set of features to grow each decision tree.

These decision trees then have their out of bag error detern sed(error rate of the model) and then the collection of decision trees are compared to find the joint set of variables that produce the strongest classification method.

The **sklearn.ensemble** module contains the **RandomForestClassifier** class that is used to train the machine learning model using the random forest algorithm.

To do so, we need to call the fit method on the **RandomForestClassifier** class and pass it our training features and labels, as parameters.

**n_estimators** is the number of trees to be used in the forest or number of samples on which this algorithm will work then it will aggregate them to give you the final answer.

Since Random Forest is an ensemble method comprising of creating multiple decision trees, this parameter is used to control the number of trees to be used in the process.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

# Making Predictions and Evaluating the Model

Once the model has been trained, the last step is to make predictions on the model. To do so, we need to call the predict method on the object of the RandomForestClassifier class that we used for training.

In [ ]:
predictions = text_classifier.predict(X_test)

# Model evaluation

To evaluate the performance of the machine learning models, we can use classification metrics such as a confusion metrix, F1 measure, accuracy, etc.

To find the values for these metrics, we can use classification_report, confusion_matrix, and accuracy_score utilities from the sklearn.metrics

A Classification report is used to measure the quality of predictions from a classification algorithm. How many predictions are True and how many are False. More specifically, True Positives, False Positives, True negatives and False Negatives are used to predict the metrics of a classification report.

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predictions))

[[1716  107   47]
 [ 331  242   41]
 [ 138   62  244]]


**Precision** quantifies the number of positive class predictions that actually belong to the positive class.

**Recall** quantifies the number of positive class predictions made out of all positive examples in the dataset.

**F-Measure** provides a single score that balances both the concerns of precision and recall in one number.

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

    negative       0.79      0.92      0.85      1870
     neutral       0.59      0.39      0.47       614
    positive       0.73      0.55      0.63       444

    accuracy                           0.75      2928
   macro avg       0.70      0.62      0.65      2928
weighted avg       0.74      0.75      0.73      2928



**Accuracy**

In [ ]:
print(accuracy_score(y_test, predictions))

0.7520491803278688
